### ISSUE TITLE
ssh-key

### ISSUE THREAD

**Issue by sfwn** [sfwn/ideas#4]
### ssh-keygen

`-C`参数 后面一般是写邮箱，例如：sfwnlin@gmail.com
但是不写的话也可以生成，而且我用同一个sshkey在gitlab和github上都可以使用

**Comment by sfwn** [comment]
我的猜想：邮箱仅仅是给你自己看的，是 comment，所以不影响 key 的生成。

**Comment by is** [comment]
仅仅是comment，方便以后目测识别，而且不一定需要邮箱地址。

**Comment by sfwn** [comment]
@is  
谢谢你的回答！  
你是如何发现这个issue的呢

**Comment by is** [comment]
忘了搜索啥东西，跳到了http://issuehub.io/ ,然后就看到你这个问题了，点了一下进来就顺手敲两行字。

**Comment by sfwn** [comment]
Thanks!  @is
